//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctus.PruebaTecnica.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
        public System.DateTime Creado { get; set; }
        public Nullable<System.DateTime> Modificado { get; set; }
    }
}
